# Generated by Django 5.1.1 on 2024-10-03 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, verbose_name='Expiration Date')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expiration_tracker.itemtype')),
            ],
        ),
    ]
