# Generated by Django 5.1.1 on 2024-10-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expiration_tracker', '0002_alter_pantryitem_expiration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pantryitem',
            old_name='item_name',
            new_name='brand',
        ),
    ]
